### ISSUE TITLE
wwwroot/app/core/services/notificationService.ts(5,30): error TS2304: Cannot find name 'alertify'.

### ISSUE THREAD

**Issue by neilyoung** [chsakell/aspnet5-angular2-typescript#1]
Got this on a Mac. Could resolve by adding 

declare var alertify: any

in line 3 of notificationService.ts

**Comment by chsakell** [comment]
It used to happen in all operating systems. The error is TypeScript oriented but doesn't cause any error when deployed on client cause we configured the <i>tsconfig.json</i> by defining:  <strong>"noEmitOnError": false</strong>. 
The suggestion is right with more info <a href="https://github.com/chsakell/aspnet5-angular2-typescript/commit/30ddb43cf4cef772b3ca761ab7ac3d355b927196">here</strong>.
