### ISSUE TITLE
Missing Lib folder. Visual studio 2015 community

### ISSUE THREAD

**Issue by MyEidos** [chsakell/aspnet5-angular2-typescript#10]
I think it is my mistake in something, but i do not have lib folder in webroot, so i get errors about missing js and css files. I have tried to restore npm packages but result was the same. Could you please help with this?  I use Visual studio 2015 community edition.

**Comment by chsakell** [comment]
You need to run the **build-spa** gulp task to create those files. Read carefully the [README.md](https://github.com/chsakell/aspnet5-angular2-typescript) file or the [post](http://chsakell.com/2016/01/01/cross-platform-single-page-applications-with-asp-net-5-angular-2-typescript/).

**Comment by MyEidos** [comment]
Yeah. Sorry. I am noob in compiling front-end, lol.  The blog post is more detailed, i have not noticed it (big header banner is not enough, lol), maybe it will be good to add link and not banner (since all banners are in association with advert).
Anyway - thanks!
