### ISSUE TITLE
IE11 - "Object doesn't support property or method 'keys'"

### ISSUE THREAD

**Issue by jecourtney** [chsakell/aspnet5-angular2-typescript#11]
Awesome article!

It works fine in Chrome, but debugging w/ IE11 results in:
"Object doesn't support property or method 'keys'" in app.js (Angular2) related I think, all I can find says to include es6-shim.js, which you do in the gulp.  I tried moving it earlier in gulp, but no luck???

Anyone have a solution?

Thanks!

**Comment by jecourtney** [comment]
I fixed this in IE11 by adding the following shims to _Layout.cshtml directly after stylesheets:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
<script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
```

Referece: https://github.com/angular/angular/issues/7144 (Ward Bell, Feb 28)

**Comment by rlekkr** [comment]
Viva shims_for_IE.js :dancers:
