### ISSUE TITLE
State Error TS6053	node_modules/angular2/typings/browser.d.ts' not found. PhotoGallery	aspnet5-angular2-typescript\src\PhotoGallery\wwwroot\app\app.ts

### ISSUE THREAD

**Issue by gacostab** [chsakell/aspnet5-angular2-typescript#16]
I keep getting this error everytime I try to compile. 

I check your blog and originally it was

`///<reference` path="../../typings/browser.d.ts" `/>`

You suggest to change it to 
`///<reference` path="../../node_modules/angular2/typings/browser.d.ts" `/>`

However, the gulp build-spa fails when I try to compile with any of the options.

![error_ts](https://cloud.githubusercontent.com/assets/19768984/15843919/4abec4ec-2ca9-11e6-91f0-18c7ad579c0b.PNG)

or by cmd

![error_ts2](https://cloud.githubusercontent.com/assets/19768984/15843936/6b8057d6-2ca9-11e6-9197-42e1bfd34545.PNG)

Could you please help me solve this.

**Comment by VahidN** [comment]
@gacostab [follow this answer for issue #1](https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-217960231)
for issue#2, [follow this answer](http://stackoverflow.com/a/36999540/298573).

**Comment by chsakell** [comment]
There's a _typings.json_ under the root of the application

``` javascript
{
    "ambientDependencies": {
        "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
        "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
        "node": "registry:dt/node#4.0.0+20160509154515"
    }
}
```

Run the following command in the console:
**typings install**

**Comment by VahidN** [comment]
@chsakell 
Now AngularJS 2.0 is using `core-js` instead of `es6-shim`. [more info](https://github.com/angular/quickstart/blob/master/typings.json)
Also you can add

``` json
  "scripts": {
    "postinstall": "typings install"
  },
```

to your `package.json` file to install typings automatically.
