### ISSUE TITLE
Issues in nick-anykeydesigns/aspnet5-angular2-typescript fork to InMemDB

### ISSUE THREAD

**Issue by gacostab** [chsakell/aspnet5-angular2-typescript#17]
Hi. 

I was testing the fork from nick-anykeydesigns/aspnet5-angular2-typescript, specially about the branch InMemDB. That branch work locally in my Windows 10 Dev environment. However, if you try to run it in Fedora 23. Kestrel server simply does not respond any commands.

![dnx_stop](https://cloud.githubusercontent.com/assets/19768984/15845402/10e401da-2cb6-11e6-8600-d5525bb4f667.PNG)

I think the original version present in master is more stable to test it in Linux servers. I will like to know what changes are required to connect the original example to MysSql server instead of MSSql. 

Could you please give a some info about that.  By the way, I really like your website.

**Comment by chsakell** [comment]
Get the latest verion of this repo and try to set **"InMemoryProvider": true** in the [appsettings.json](https://github.com/chsakell/aspnet5-angular2-typescript/blob/master/src/PhotoGallery/appsettings.json). I made this addition for those who cannot use SqlServer.
