### ISSUE TITLE
Cannot restore

### ISSUE THREAD

**Issue by pawannepal** [chsakell/aspnet5-angular2-typescript#22]
Cannot restore: I get the following errors in the project.json file. Can you please guide me through this.

Error   NU1002  The dependency Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.  PhotoGallery    C:\Downloads\aspnet5-angular2-typescript-master\aspnet5-angular2-typescript-master\src\PhotoGallery\project.json    15  
Error   NU1002  The dependency Microsoft.AspNetCore.Mvc.TagHelpers 1.0.0 does not support framework .NETCoreApp,Version=v1.0.   PhotoGallery    C:\Downloads\aspnet5-angular2-typescript-master\aspnet5-angular2-typescript-master\src\PhotoGallery\project.json    16

**Comment by chsakell** [comment]
I suppose you got this error in Visual Studio. Make sure to install both <a href="https://go.microsoft.com/fwlink/?LinkId=691129">Visual Studio 2015 Update 3</a> and the <a href="https://go.microsoft.com/fwlink/?LinkID=824849">.NET Core 1.0.0 - VS 2015 Tooling Preview 2</a>.

**Comment by pawannepal** [comment]
Yes, I get this error in Visual Studio. I have been using these updates for some time now ( VS 2015 update 3 and tooling preview 2 both). But still i get this error. I have tried in different system as well, and get the same error. Do you think I am missing something.

**Comment by chsakell** [comment]
I can't reproduce your issue and no one else has reported the same. Make sure to have at least the latest dotnet version

```
dotnet --version
```

```
1.0.0-preview2-003121
```
