### ISSUE TITLE
After reload page browser restore url

### ISSUE THREAD

**Issue by alexey-gorshkov** [chsakell/aspnet5-angular2-typescript#25]
After the update the browser page to restore the old page Url. Now there is a transition at the Home page.

**Comment by chsakell** [comment]
remove the _this.location.go('/'); from the app.component.ts_

```
ngOnInit() {
   //this.location.go('/');
}
```

Make sure you rebuild the spa before trying it.

**Comment by alexey-gorshkov** [comment]
Thank you! I thought that the routing problem. You helped me!
