### ISSUE TITLE
Cannot open database?

### ISSUE THREAD

**Issue by Caballep** [chsakell/aspnet5-angular2-typescript#26]
Im having this error:
**_An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: Cannot open database "PhotoGallery" requested by the login. The login failed._**

At this line:

**_if (!context.Albums.Any())_** inside DbInitializer.cs

**Comment by chsakell** [comment]
Did you follow the exact [instructions](https://github.com/chsakell/aspnet5-angular2-typescript/blob/master/README.md) and create the required database? What is your connection string in the **appsettings.json**?
