### ISSUE TITLE
Update .NET Core 1.1

### ISSUE THREAD

**Issue by alexey-gorshkov** [chsakell/aspnet5-angular2-typescript#27]
Hi, Announcing .NET Core 1.1. 
[news](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/)

and update package angular. Now "@angular/common": "~2.2.0" ...

**Comment by chsakell** [comment]
[upgrade to .net core 1.1](https://github.com/chsakell/aspnet5-angular2-typescript/commit/0ad06f376e93cb738c56740ad7faad5bd6e1a710)
[upgrade angular to 2.2](https://github.com/chsakell/aspnet5-angular2-typescript/commit/4d2ffc54bb565c9c4d428b7b479fa77559f60d74)
