### ISSUE TITLE
This proj doesnot work, sign in page does not show

### ISSUE THREAD

**Issue by sbg123** [chsakell/aspnet5-angular2-typescript#30]
http://localhost:9823/lib/css/alertify.bootstrap.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9823/lib/css/alertify.core.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9823/lib/js/alertify.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.js:2785 Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)
http://localhost:9823/lib/js/alertify.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9823/lib/css/alertify.core.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9823/lib/css/alertify.bootstrap.css Failed to load resource: the server responded with a status of 404 (Not Found)

**# while running npm install, getting this** 

typings WARN deprecated 5/10/2016: # "registry:dt/es6-shim#0.31.2+20160317120654" is deprecated (updated, replaced or removed)
typings WARN deprecated 4/28/2016: "registry:dt/body-parser#0.0.0+20160317120654" is deprecated (updated, replaced or removed)
typings WARN deprecated 10/25/2016: "registry:dt/jasmine#2.2.0+20160621224255" is deprecated (updated, replaced or removed)
typings WARN deprecated 4/28/2016: "registry:dt/cookie-parser#1.3.4+20160316155526" is deprecated (updated, replaced or removed)
typings WARN deprecated 4/27/2016: "registry:dt/express#4.0.0+20160317120654" is deprecated (updated, replaced or removed)
typings WARN deprecated 5/10/2016: "registry:dt/express-serve-static-core#0.0.0+20160322035842" is deprecated (updated, replaced or removed)
typings WARN deprecated 4/28/2016: "registry:dt/mime#0.0.0+20160316155526" is deprecated (updated, replaced or removed)
typings WARN deprecated 4/27/2016: "registry:dt/serve-static#0.0.0+20160317120654" is deprecated (updated, replaced or removed)

npm update works
bower is installed

installed all mentioned packages, pls help me set and run this project

**Comment by chsakell** [comment]
The project works fine as used to, it's you that you didn't make it. 
First, don't worry about the warnings. From the 404 errors its seems that either you haven't installed bower components or most likely you didn't run the **build-spa** gulp task that prepares the app. Read the [README.md](https://github.com/chsakell/aspnet5-angular2-typescript/blob/master/README.md) file again.

**Comment by sbg123** [comment]
bower installed properly but bower_component does not contain the files which are missing, 
alertify.bootstrap.css 
alertify.core.css 
alertify.min.js  
..
..
pls tell me whats is wrong here, i have followed README.md like 6 times. Everytime same result

**Comment by sbg123** [comment]
i get this error too 
Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)
