### ISSUE TITLE
EF migration error with the source code for VS2017

### ISSUE THREAD

**Issue by kflili** [chsakell/aspnet5-angular2-typescript#31]
I clone the new version code from here and opened in VS2017. Followed the install instruction in the ReadMe. Build success. When I use try to do EF migration, I got following errors.

C:\Projects\aspnet6-angular2-typescript\src\PhotoGallery>dotnet ef migrations add initial

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.44
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
No parameterless constructor was found on 'PhotoGalleryContext'. Either add a parameterless constructor to 'PhotoGalleryContext' or add an implementation of 'IDbContextFactory<PhotoGalleryContext>' in the same assembly as 'PhotoGalleryContext'.

**Comment by chsakell** [comment]
Apply [these](https://github.com/chsakell/aspnet5-angular2-typescript/commit/39ef4ed99a4e641ae816cc54d4ce493ad499a050) changes (_run git pull_) and try again.
[Reference](https://github.com/aspnet/Announcements/issues/209)

**Comment by kflili** [comment]
Thanks, Christos! That works!
