### ISSUE TITLE
wwwroot is no longer a property in project.json

### ISSUE THREAD

**Issue by neilyoung** [chsakell/aspnet5-angular2-typescript#5]
As a last minute change it has been placed in hosting.json now

**Comment by chsakell** [comment]
No need for that.

**Comment by neilyoung** [comment]
Basically I found it while trying to follow this video 

https://channel9.msdn.com/Events/Build/2015/2-675

in my VS 2015 SP1 project. Starting around minute 10 the guy demonstrates, how the wwwroot folder could be deleted, if the webroot was changed in project.json.

I tried that and it didn’t work. I was not even having intellisense support for „webroot“ in that file. I could not delete wwwroot.

After sniffing around I came across this:

https://github.com/aspnet/Announcements/issues/94

tried it and - boom I was able to delete the folder :)

**Comment by neilyoung** [comment]
BTW: The title should be "webroot" is no longer a property... but you got it I think

**Comment by chsakell** [comment]
Once again, it's irrelevant to our project. Just because it's possible to change the <i>wwwroot</i> folder, doesn't mean we have to change this project as well. The issue is invalid and <i>webroot</i> remains in the <i>project.json</i> synced with the source code. Let's close this issue here.
