### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by tuppers360** [chsakell/aspnet5-angular2-typescript#7]
Hi Christos,

Not sure this is the correct place to contact you re my issue, I have forked your repo and opened it in VS 2015 and tried to run the app but get a strange error:

Error: Object doesn't support property or method 'keys'
        Error loading http://localhost:9823/lib/spa/app.js

The spinning wheel is displayed but the app hangs and nothing happens.

I am not sure what this means? The only thing I have change is the connection string for the app to run on my machine. This works fine as I have run the scripts for EF to create the db locally, can you please advise?

Many thanks

Sorry if this is not the place to contact you regarding the issue.

Oh and running on Windows

**Comment by johnpankowicz** [comment]
Could you possibly be using an old version of IE? The keys property is supported in IE >= 9.

**Comment by tuppers360** [comment]
Hi running the app in IE11 and Edge, just trying Chrome and Firefox out now.

Thanks

Edit: Appears that after installing Firefox and Chrome the site works in Edge but not IE11, very strange.

**Comment by tuppers360** [comment]
Mmmmm.... I think I have found the issue.

The following is added to the site when it renders: 

`<script type="text/javascript" src="http://ie.kis.scr.kaspersky-labs.com/1B74BD89-2A22-4B93-B451-1C9E1052A0EC/main.js" charset="UTF-8">`

But the line does not appear in Edge, Firefox & Chrome and they render perfectly happily so I will close the thread.

Thanks for taking the time to look at this.
